cache:
  directories:
  - ".cache"
  - node_modules/
  - "$HOME/.propel/cache"
branches:
  only:
  - master
language: node_js
os:
- linux
# - osx -- disabled because of Travis CI downtime/backlog
git:
  submodules_depth: 1
node_js:
- '8.8'
script:
- "./tools/presubmit.js"
- "./tools/deploy_github_pages.js"
env:
  global:
    secure: t5IKMtjbwr+JptV50kMiVK1LNqihPmIpnZGjqTbRzUIkl4u0+SR0BLCGR85WanYTBWFHepyRx4lgxIc8IsekxiOANUz8Idl1/eQJKlcdHxboU14vpRn0zsQ0/qlhVCHXoQAkqBQk3mViMSDqHEXAq5xXOln3d9i32ERg9A1/yBx9DbNShmJ9VJwIPBBLtn5WBZkqlW4XITFTheUJgDR6aqXVNEEasirFSP/3OuKQN7L0coB1KQ/Q/Sgh/8ilDmqWibU8Q3+0ozNVZ4DLAVwqJemXjQEZqXq+7eW5EvuDc8TMKruW1wAVNjIQKH2DYsr0Mlv7CY+7nLxw+NEdM0AV0WNXx0ouao1F1NjJ8Ev+wzqm/HbkLo10hRDWpnGzdSU02+E2Dbz3Urw7J4ibLqMvLXqfZoKwO6cdk+ziqB4cQIm4TzdMRSVNN6ObkvhnX+nOtn18dBkXQD5CaQqnXDPaE+P8fV95PSQUYOLl4RjYCRGD20rpoOYAllWqkPReMSTA1oW+ygdGXaoYJ/EStUz81/mNh5qSFaEYwsaJFiov7HQYpiy6auEoOYGyGvbWEw+aQSDqkCUK9bd+iLQQ4zKe8EPbVgPII2Y9JfQqDrswozi+M7XPoJe06tE4rjtkR10n0nd9qOt260AV/sqXTbVMF1/pa8ZdxpF8NEGV3/vOI8c=
