AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: denoland3
Globals:
    Function:
        Timeout: 3


Resources:

    DenoLandFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: x/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                DenoLand:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /x
                        Method: get

Outputs:

    DenoLandApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    DenoLandFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt DenoLandFunction.Arn

    DenoLandFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt DenoLandFunctionRole.Arn
